/*
 * Salesforce DTO generated by camel-salesforce-maven-plugin
 */
package org.apache.camel.salesforce.dto;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Salesforce Enumeration DTO for picklist ForecastCategory
 */
@Generated("org.apache.camel.maven.CamelSalesforceMojo")
public enum Opportunity_ForecastCategoryEnum {

    // BestCase
    BESTCASE("BestCase"),

    // Closed
    CLOSED("Closed"),

    // Forecast
    FORECAST("Forecast"),

    // MostLikely
    MOSTLIKELY("MostLikely"),

    // Omitted
    OMITTED("Omitted"),

    // Pipeline
    PIPELINE("Pipeline");

    final String value;

    private Opportunity_ForecastCategoryEnum(String value) {
        this.value = value;
    }

    @JsonValue
    public String value() {
        return this.value;
    }

    @JsonCreator
    public static Opportunity_ForecastCategoryEnum fromValue(String value) {
        for (Opportunity_ForecastCategoryEnum e : Opportunity_ForecastCategoryEnum.values()) {
            if (e.value.equals(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException(value);
    }
}
